### ISSUE TITLE
Bug: panic pi^e

### ISSUE THREAD

**Issue by pjebs** [Sandertv/go-formula#5]
```go
package main

import (
	"github.com/sandertv/go-formula/v2"
	"log"
)

func main() {
	f, err := formula.New("pi^e")
	if err != nil {
		log.Print(err)
		return
	}
	x := formula.Var("x", 4.5)
	z := formula.Var("z", 5)
	log.Printf("Formula output: %v", f.Eval(x, z))
}
```

See: https://play.golang.org/p/-Kit-m2jbhK
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4c84e1]

goroutine 1 [running]:
github.com/sandertv/go-formula/v2.(*Formula).Eval(0xc000096280, 0xc0000a0f48, 0x2, 0x2, 0x0)
	/tmp/gopath030862853/pkg/mod/github.com/sandertv/go-formula/v2@v2.0.0-alpha.3/formula.go:64 +0x281
main.main()
	/tmp/sandbox655706046/prog.go:16 +0x15e
```

**Comment by pjebs** [comment]
It would be good if `a^b` was implemented as `math.Pow(a,b)`

**Comment by pjebs** [comment]
```go
case token. XOR:
		eval = func(vars vars) float64 {
			return   math.Pow(x(vars),  y(vars))
		}
```

**Comment by Sandertv** [comment]
Due to the way Go uses `^` as `xor` instead of pow, `^` has lower precedence than other operators like `+`. That might be a problem.

**Comment by pjebs** [comment]
Good point. At least it shouldn't panic.

**Comment by Sandertv** [comment]
I reckon it would be better to just return an error rather than behaviour that is essentially incorrect?

**Comment by pjebs** [comment]
Yes the function should never panic and just return an error

**Comment by Sandertv** [comment]
Fxed in 1cf4d7bb84c8b90fe62cb0238c5e3c79c5dd2c93.
